### ISSUE TITLE
self-signed cert error

### ISSUE THREAD

**Issue by robhicks** [joshnuss/svelte-supabase#2]
I am using your package. Thanks for creating it. 

I have wired things up like this:
```JavaScript
// src/lib/db.js
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY
)

export default supabase
```JavaScript
// src/hooks.js
import supabase from '$lib/db';

export async function getContext({ req, headers }) {
  console.log(`req`, req)
  const [ user, { data } ] = await Promise.all([
    supabase.auth.user(),
    supabase.from('translations').select('en')
  ])

	return {
		user: user || { guest: true },
    translations: data
	};
}
```
When the hook runs, the following error appears in the console:
```shell
FetchError: request to https://vfqgxrbhsubjxhufqdev.supabase.co/rest/v1/translations?select=en failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/home/robhicks/personal/savvagent/green-warrior/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Can you help me understand why and give me some direction on fixing it?

**Comment by robhicks** [comment]
The call to the translations table is triggering the error. I have not yet enabled Row Level Security. Do I need to in order for the request to succeed?

**Comment by joshnuss** [comment]
Hi @robhicks,

Haven't tried it with hooks, is `supabase.auth.user()` returning a user?

I believe `getContext()` runs on the server, so you need to use the user's supabase `accessToken` instead of the `env.VITE_SUPABASE_ANON_KEY` if you want to run commands a specific user.

There are a few ways to do that.

I have been thinking about expanding the `db.js` to support a few different scenarios. There are actually 3 scenarios:

1. Public access, client-side or server-side. This uses the anon key.
2. Protected access, server-side only. This uses the private key.
3. Impersonating access, server-side only. This uses the access token of the user. (I think that is what you're after here).

The API could look something like:

```javascript
import db from 'supabase'

db.anon.from('...') // public/anon key
db.protected.from('...') // private key. not available client side
db.identity(accessToken).from('...) // access token, not available client side
```

That's the rough idea, I gotta think about it a bit more.

**Comment by robhicks** [comment]
I fixed this by moving supabase to devDependencies. 

I like your ideas and agree that option 3 would be ideal for my use case.

**Comment by joshnuss** [comment]
Since it's fixed, i'm closing the issue.
